--creacionRoleMaster
CREATE TABLE ROLEMASTER(
    ROL INTEGER PRIMARY KEY,
    FECHACOMPUTO DATE,
    DESCRIPCION VARCHAR2(30),
    ESTADOREGISTRO NUMBER(1),
    CODUSUARIO INT
);

--creacionWAYPAYMASTER
CREATE TABLE WAYPAYMASTER (
    WAYPAY INTEGER PRIMARY KEY,
    FECHACOMPUTO DATE,
    DESCRIPCION VARCHAR2(30),
    ESTADOREGISTRO NUMBER(1),
    CODUSUARIO INT
);

--creacionPRODUCTMASTER
CREATE TABLE PRODUCTMASTER (
    RAMO INTEGER,
    PRODUCTO INTEGER,
    FECHACOMPUTO DATE,
    DESCRIPCION VARCHAR2(30),
    ESTADOREGISTRO NUMBER(1),
    CODUSUARIO INT,
    PRIMARY KEY (RAMO, PRODUCTO)
);

--creacionBranch
CREATE TABLE BRANCHMASTER (
    RAMO INTEGER PRIMARY KEY,
    FECHACOMPUTO DATE,
    DESCRIPCION VARCHAR2(30),
    ESTADOREGISTRO NUMBER(1),
    CODUSUARIO INT
);