--creacionRoleMaster
CREATE TABLE DOCUMENTOS (
    DOCTYPE         NUMBER,
    DOCUMENTO       VARCHAR2(50),
    CLIENTE         VARCHAR2(50),
    CUIL_CUIT_DNI   NUMBER(10),
    FECHAEXPIRACION DATE,
    CONSTRAINT pk_documentos PRIMARY KEY (DOCTYPE, DOCUMENTO, CLIENTE, CUIL_CUIT_DNI)
);

--creacionClientes
CREATE TABLE CLIENTES(
    CLIENTE             VARCHAR2(50) PRIMARY KEY,
    NOM_COMPLETO        VARCHAR2(50),
    FECHA_NACIMIENTO    DATE,
    NULLDATE            DATE null,
    ESTADO_CIVIL        INT
);